{% set name = "cupy" %}
{% set version = "7.0.0" %}
{% set sha256 = "b67a4bafc1fb5f5625051c38c6bbf126bfc04f23929b0cd93c59a8590334a887" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cupy/cupy/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [(not linux64) or cuda_compiler_version == "None"]
  script:
    # CUDA 10.1 moves some headers to `/usr/include`
    # So add that location last in the header search paths
    - export CFLAGS="${CFLAGS} -I/usr/include"
    - export CPPFLAGS="${CPPFLAGS} -I/usr/include"
    - export CXXFLAGS="${CXXFLAGS} -I/usr/include"
    - "{{ PYTHON }} -m pip install . -vv"
  missing_dso_whitelist:
    - "*/libcuda.*"

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}

  host:
    - python
    - pip
    - setuptools
    - cython >=0.24.0
    - cudnn
    - fastrlock >=0.3
    - nccl

  run:
    - python
    - setuptools
    - cudnn
    - fastrlock >=0.3
    - numpy >=1.9.0
    - six >=1.9.0

test:
  requires:
    - pytest
    - mock
  source_files:
    - tests

about:
  home: https://cupy.chainer.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CuPy is an implementation of a NumPy-compatible multi-dimensional array on CUDA.

extra:
  recipe-maintainers:
    - jakirkham
    - leofang
    - kmaehashi
    - beam2d
    - asi1024
    - emcastillo
    - hvy
    - niboshi
    - toslunar 
